version: '3.8'

services:
  service:
    build:
      context: .
    container_name: service
    depends_on:
      - postgredb
      - rabbitmq
      - elasticsearch
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mysecretpassword
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/flightsdb
      - SPRING_DATASOURCE_USERNAME=myusername
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=myusername
      - RABBITMQ_PASSWORD=mysecretpassword
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - "8080:8080"

  postgredb:
    image: postgres:15-alpine
    container_name: postgredb
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=flightsdb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./db/postgre/init_db.sql:/docker-entrypoint-initdb.d/01-init_db.sql
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myusername
      - RABBITMQ_DEFAULT_PASS=mysecretpassword

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  esdata:
  postgresdata:
